name: pytest
on: [push, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv codecov
        pip install -r requirements.txt
        pipenv install --dev
    - name: Test with pytest
      run: |
        sudo mkdir /var/log/s3_upload
        sudo chmod o+w /var/log/s3_upload
        pytest -v --cov --cov-report xml --count 10 --random-order tests/unit/
        total=$(head -n2 coverage.xml | grep -Po '(?<=line-rate=\").*?(?=")')
        echo $total
    - name: "Make badge"
      uses: schneegans/dynamic-badges-action@v1.4.0
      with:
        # GIST_TOKEN is a GitHub personal access token with scope "gist".
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: d591ef748f8a2c40c21ceedcad88a80e   # replace with your real Gist id.
        filename: covbadge.json
        label: Coverage
        message: ${{ env.total }}%
        minColorRange: 50
        maxColorRange: 90
        valColorRange: ${{ env.total }}
